version: "3.8"
services:
  gym-postgres:
    image: postgres:16
    container_name: gym-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gymcrm
      POSTGRES_USER: gym_user
      POSTGRES_PASSWORD: gym_pass
    ports:
      - "5432:5432"
    volumes:
      - gym_pg_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gym_user -d gymcrm" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  gym_pg_data: