spring:
  application:
    name: gym-crm
  profiles:
    active: local

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

server:
  port: 8080

spring:jackson.serialization.write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always